# Generated by Django 3.0.3 on 2020-04-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200426_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
