# Generated by Django 3.0.3 on 2020-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200427_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
