# Generated by Django 3.0.3 on 2020-04-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200427_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='assigned_to_emp_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_emp', to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='functional_area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.FunctionalAreas'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='priority',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Priorities'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='resolution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resol', to='app.Resolutions'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='resolution_version',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resol_version', to='app.Resolutions'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
        ),
    ]
