# Generated by Django 3.0.3 on 2020-04-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200427_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='assigned_to_emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_emp', to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resol', to='app.Resolutions'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='resolution_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resol_version', to='app.Resolutions'),
        ),
    ]
