# Generated by Django 3.0.3 on 2020-04-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200427_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='functional_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FunctionalAreas'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Priorities'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
        ),
    ]
