# Generated by Django 3.0.3 on 2020-04-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200427_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='resolved_by_emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_emp', to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='resolved_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='tested_by_emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tested_emp', to='app.Employees'),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='tested_on_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
