# Generated by Django 3.0.3 on 2020-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200428_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='resolution_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='suggested_fix',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
